---
- gather_facts: false
  name: Unsubscribe container
  hosts: all
  tasks:
    - name: Unsubscribe container
      command: subscription-manager unregister
      ignore_unreachable: true
      ignore_errors: true
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version is version("6", "==")
