---
- gather_facts: false
  name: Setup RHEL6
  hosts: all
  tasks:
    - name: Subscribe container
      redhat_subscription:
        auto_attach: true
        force_register: true
        password: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD') }}"
        username: "{{ lookup('env','REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME') }}"
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version is version("6", "==")

    - name: Install packages
      yum:
        name:
          - sudo
          - tar
        state: present
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version is version("6", "==")

